#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const VALHALLA_URL = 'https://valhalla1.openstreetmap.de/route';
const DELAY_MS = 1500;

function decodePolyline(encoded, factor = 1e5) {
    const points = [];
    let index = 0, lat = 0, lng = 0;
    while (index < encoded.length) {
        let b, shift = 0, result = 0;
        do { b = encoded.charCodeAt(index++) - 63; result |= (b & 0x1f) << shift; shift += 5; } while (b >= 0x20);
        lat += (result & 1) ? ~(result >> 1) : (result >> 1);
        shift = 0; result = 0;
        do { b = encoded.charCodeAt(index++) - 63; result |= (b & 0x1f) << shift; shift += 5; } while (b >= 0x20);
        lng += (result & 1) ? ~(result >> 1) : (result >> 1);
        points.push([lat / factor, lng / factor]);
    }
    return points;
}

function encodePolyline(points, factor = 1e5) {
    let output = '';
    let prevLat = 0, prevLng = 0;
    for (const [lat, lng] of points) {
        const latRound = Math.round(lat * factor);
        const lngRound = Math.round(lng * factor);
        output += encodeValue(latRound - prevLat);
        output += encodeValue(lngRound - prevLng);
        prevLat = latRound;
        prevLng = lngRound;
    }
    return output;
}

function encodeValue(value) {
    let v = value < 0 ? ~(value << 1) : (value << 1);
    let encoded = '';
    while (v >= 0x20) {
        encoded += String.fromCharCode((0x20 | (v & 0x1f)) + 63);
        v >>= 5;
    }
    encoded += String.fromCharCode(v + 63);
    return encoded;
}

const MAX_WAYPOINTS = 20;

async function fetchRouteChunk(points) {
    const locations = points.map(([lat, lng]) => ({ lat, lon: lng, type: 'break' }));
    const body = JSON.stringify({ locations, costing: 'auto' });

    const res = await fetch(VALHALLA_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body
    });

    if (!res.ok) {
        const text = await res.text();
        throw new Error(`Valhalla ${res.status}: ${text.slice(0, 200)}`);
    }

    const data = await res.json();
    if (!data.trip || !data.trip.legs) {
        throw new Error('No trip.legs in Valhalla response');
    }

    let all = [];
    data.trip.legs.forEach((leg, i) => {
        const pts = decodePolyline(leg.shape, 1e6);
        all = all.concat(i === 0 ? pts : pts.slice(1));
    });
    return all;
}

async function fetchRoute(points) {
    if (points.length <= MAX_WAYPOINTS) {
        return fetchRouteChunk(points);
    }

    let all = [];
    for (let start = 0; start < points.length - 1; start += MAX_WAYPOINTS - 1) {
        const end = Math.min(start + MAX_WAYPOINTS, points.length);
        const chunk = points.slice(start, end);
        if (chunk.length < 2) break;
        if (start > 0) await sleep(DELAY_MS);
        const pts = await fetchRouteChunk(chunk);
        all = all.concat(start === 0 ? pts : pts.slice(1));
    }
    return all;
}

function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

async function main() {
    const dataCode = fs.readFileSync(path.join(__dirname, 'data.js'), 'utf8');
    const fn = new Function(dataCode + '\nreturn MOVIES;');
    const MOVIES = fn();

    const cachedRoutes = {};

    for (const [slug, movie] of Object.entries(MOVIES)) {
        if (!movie.JOURNEYS) continue;
        cachedRoutes[slug] = {};

        for (const [key, journey] of Object.entries(movie.JOURNEYS)) {
            const wp = journey.points;
            if (!wp || wp.length < 2) {
                console.log(`  [skip] ${slug}/${key} — fewer than 2 waypoints`);
                continue;
            }

            console.log(`  Fetching ${slug}/${key} (${wp.length} waypoints)...`);
            try {
                const decoded = await fetchRoute(wp);
                const encoded = encodePolyline(decoded, 1e5);
                cachedRoutes[slug][key] = encoded;
                console.log(`    ✓ ${decoded.length} points → ${encoded.length} chars`);
            } catch (err) {
                console.error(`    ✗ ${err.message}`);
            }

            await sleep(DELAY_MS);
        }
    }

    let js = '// Pre-cached road-routed journey geometry (encoded polyline, precision 5)\n';
    js += '// Generated by regen_routes.js — do not hand-edit\n';
    js += '// Regenerate: node regen_routes.js\n';
    js += 'const CACHED_ROUTES = {\n';

    const slugs = Object.keys(cachedRoutes);
    slugs.forEach((slug, si) => {
        js += `${JSON.stringify(slug)}: {\n`;
        const keys = Object.keys(cachedRoutes[slug]);
        keys.forEach((key, ki) => {
            const polyStr = JSON.stringify(cachedRoutes[slug][key]);
            js += `    ${JSON.stringify(key)}: ${polyStr}`;
            js += ki < keys.length - 1 ? ',\n' : '\n';
        });
        js += '}';
        js += si < slugs.length - 1 ? ',\n' : '\n';
    });

    js += '};\n';

    const outPath = path.join(__dirname, 'routes.js');
    fs.writeFileSync(outPath, js, 'utf8');
    console.log(`\nWrote ${outPath} (${js.length} bytes)`);

    // Verify round-trip: decode every stored polyline and check first/last points
    console.log('\nVerification:');
    for (const [slug, routes] of Object.entries(cachedRoutes)) {
        for (const [key, encoded] of Object.entries(routes)) {
            try {
                const pts = decodePolyline(encoded, 1e5);
                console.log(`  ${slug}/${key}: ${pts.length} pts, first=[${pts[0][0].toFixed(4)},${pts[0][1].toFixed(4)}], last=[${pts[pts.length-1][0].toFixed(4)},${pts[pts.length-1][1].toFixed(4)}]`);
            } catch (e) {
                console.error(`  ${slug}/${key}: DECODE FAILED — ${e.message}`);
            }
        }
    }

    // Verify no unescaped characters in the output file
    const written = fs.readFileSync(outPath, 'utf8');
    try {
        new Function(written);
        console.log('\n✓ routes.js parses as valid JavaScript');
    } catch (e) {
        console.error(`\n✗ routes.js has JS syntax error: ${e.message}`);
    }
}

main().catch(err => {
    console.error('Fatal:', err);
    process.exit(1);
});
